In [3]:
# Q1) Combining a one and a two-dimensional NumPy Array
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6],
                 [7, 8, 9]])

result = np.vstack((arr1, arr2))
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Q2) Flatten a 2d numpy array into 1d array
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [6]:
# Q3) Reverse a numpy array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

reverse_arr = arr[::-1]
print(reverse_arr)

[50 40 30 20 10]


In [8]:
# Q4) Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy 
# (a) Maximum Value
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.max(arr))
print(np.min(arr))

50
10


In [9]:
# (c) Number of Rows and Columns
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

rows, cols = arr.shape
print(rows)
print(cols)

2
3


In [10]:
# (d) Select Elements
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)
print(arr[1, 2])

[[1 2 3]
 [4 5 6]]
6


In [13]:
# (e) Sum of Values in 2D Array using For Loop
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

total = 0

for row in arr:
    for value in row:
        total += value

print(total)

21


In [14]:
# (f) Addition, Subtraction, Multiplication, Division
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition =", a + b)
print("Subtraction =", a - b)
print("Multiplication =", a * b)
print("Division =", a / b)

Addition = [11 22 33]
Subtraction = [ 9 18 27]
Multiplication = [10 40 90]
Division = [10. 10. 10.]


In [15]:
# Q5) Iterate 3D array using for loop and nditer 
# Using For Loop
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8


In [16]:
# Using nditer
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [19]:
import numpy as np
from scipy import stats

# Create two 2D NumPy arrays
arr1 = np.array([[10, 20, 30],
                 [40, 50, 60]])

arr2 = np.array([[15, 25, 35],
                 [45, 55, 65]])

print("First Array:")
print(arr1)

print("\nSecond Array:")
print(arr2)

# Average of two arrays
avg_array = (arr1 + arr2) / 2

print("\nAverage of Two Arrays:")
print(avg_array)

# Combine both arrays into one array
combined = np.concatenate((arr1.flatten(), arr2.flatten()))

print("\nCombined Array:")
print(combined)

# Mean
mean_value = np.mean(combined)

# Median
median_value = np.median(combined)

# Mode
mode_value = stats.mode(combined, keepdims=True)

print("\nMean =", mean_value)
print("Median =", median_value)
print("Mode =", mode_value.mode[0])

First Array:
[[10 20 30]
 [40 50 60]]

Second Array:
[[15 25 35]
 [45 55 65]]

Average of Two Arrays:
[[12.5 22.5 32.5]
 [42.5 52.5 62.5]]

Combined Array:
[10 20 30 40 50 60 15 25 35 45 55 65]

Mean = 37.5
Median = 37.5
Mode = 10
