In [1]:
# Q1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]
import numpy as np

# Create Array
arr = np.array([
    [6, -8, 73, -110],[np.nan, -8, 0, 94]
])

print("Original Array:")
print(arr)


Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]


In [3]:
# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)
print(arr)

[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]


In [4]:
# Create 3x3 Array
arr2 = np.array([
    [1, 2, 3],[4, 5, 6],[7, 8, 9]
])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Interchange Rows and Columns
transpose = arr2.T
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
# Q2) Move axes of 3D array to new positions
import numpy as np

# Create 3D Array
arr = np.arange(24).reshape(2, 3, 4)

print("Original 3D Array:")
print(arr)
print(arr.shape)

Original 3D Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [8]:
# Move Axes
new_arr = np.moveaxis(arr, 0, 2)
print(new_arr)
print(new_arr.shape)

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
(3, 4, 2)


In [10]:
# Q3) Replace NaN values with average of columns 
import numpy as np

# Create Array
arr = np.array([
    [1, 2, np.nan],[4, np.nan, 6],[7, 8, 9]
])
print("Original Array:")
print(arr)

Original Array:
[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [12]:
# Find Average of Columns
col_mean = np.nanmean(arr, axis=0)

# Find NaN Positions
inds = np.where(np.isnan(arr))

# Replace NaN with Column Average
arr[inds] = np.take(col_mean, inds[1])

print(arr)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [13]:
# Q4) Replace negative value with zero in numpy array using replace
import numpy as np

# Create Array
arr = np.array([6, -8, 73, -110, 45, -67])

print("Original Array:")
print(arr)

# Replace Negative Values with 0
arr[arr < 0] = 0

print(arr)

Original Array:
[   6   -8   73 -110   45  -67]
[ 6  0 73  0 45  0]
