In [2]:
# Q1) Create numpy array and perform following operation
# 1. Convert 1D array to 2D
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2d = arr1.reshape(2, 3)
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [3]:
# 2. Print Array Attributes(Like shape, dimenssion, data type, itemsize)
print("Shape:", arr2d.shape)
print("Dimension:", arr2d.ndim)
print("Data Type:", arr2d.dtype)
print("Item Size:", arr2d.itemsize)

Shape: (2, 3)
Dimension: 2
Data Type: int64
Item Size: 8


In [5]:
# 3. Create a 3×3 NumPy array of all 9
arr = np.full((3, 3), 9)
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [6]:
# 4. Create a 1D array of 10 evenly spaced values between 25 and 125
arr = np.linspace(25, 125, 10)
print(arr)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [7]:
# 5. Convert a Python list into a NumPy array
lst = [10, 20, 30, 40]
arr = np.array(lst)
print(arr)

[10 20 30 40]


In [8]:
# 6. Reverse a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])

[5 4 3 2 1]


In [11]:
# 7. Create a 4×4×3 array and extract value at second set, first row and last column
arr = np.arange(48).reshape(4, 4, 3)
print(arr)
print(arr[1, 0, 2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
14


In [14]:
# 8. Create a 4×4 and Extract Odd Rows and Even Columns
arr = np.arange(1, 17).reshape(4, 4)
print(arr)
print(arr[::2, 1::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  4]
 [10 12]]


In [15]:
# 9. Slice first two rows and first two columns of second set from 4×4×3 array
arr = np.arange(48).reshape(4, 4, 3)
print(arr[1, :2, :2])

[[12 13]
 [15 16]]


In [16]:
# 10. Replace all odd numbers with -1 using for loop
arr = np.array([[23, 56, 78, 93],
                [71, 82, 13, 24]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:
            arr[i][j] = -1
print(arr)            

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [17]:
# 11. Get indices of non-zero elements
arr = np.array([1, 0, 2, 0, 3, 0, 4])
print(np.nonzero(arr))

(array([0, 2, 4, 6]),)


In [20]:
# 12. Arithmetic Operations on Two Arrays
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])
print(arr1 + arr2)
print(arr1 * arr2)

[11 22 33]
[10 40 90]


In [21]:
# 13. Dot Product
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot_product = np.dot(arr1, arr2)
print(dot_product)

1875
